### ISSUE TITLE
change navigation through our website

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#429]
Change navbar to:
+ About = "Our Story" + "Our Team"
+ Programme
+ London
  + Info (contains "Portfolio")
  + Prepare
  + Apply
+ Nazareth
  + Info
  + Prepare
  + Apply

It's a shame to lose "Apply" from the navbar, I know. But realistically, everything is sufficiently different in the two places (social media, press, pre-course, application form, post-course opportunities), that I think it makes more sense to divide the website, than just divide that page.

**Comment by rebeccaradding** [comment]
@jsms90 seeing it this way makes a lot of sense. So basically the "prepare" info would be in both locations rather than as one landing page for both applications?

**Comment by emilyb7** [comment]
The fun thing about the FAC website is that the navigation is so confusing, sometimes you randomly discover new pages that you never knew existed.

Just discovered (through looking at the latest PR) that we already have separate pages for London and Nazareth ✨💡😅

Definitely in favour of anything that makes these pages easier to fine!! ❤️

Are we having completely separate pages for each of info / apply / prepare in London and Nazareth though?

I don't have a better solution but I don't think we should duplicate too much content as far as possible because:
a) more work: when we want to update one thing, we potentially have to do it in multiple places
b) duplicate content can kill SEO

**Comment by rebeccaradding** [comment]
@emilyb7 Jen has updated the Google doc to reflect this proposed structure, which does not include duplicating the course prerequisites. Have a look and let us know what you think?

**Comment by emilyb7** [comment]
@rebeccaradding @jsms90 so there is a single page for prerequisites? In which case, i think that's good! Let's just make sure that everything is very clearly linked together so that pages don't get lost :))

**Comment by jsms90** [comment]
@emilyb7 Exactly. The prerequisties are currently the same in all campuses, so we might as well just have one page.

> Are we having completely separate pages for each of info / apply / prepare in London and Nazareth though?

Yes, completely separate pages, because the content in all 3 elements currently depend on location :+1:
