### ISSUE TITLE
FAC10 photo: file size is too big

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/our-site#431]
Related to #413 

This PR was merged over a month ago but doesn't seem to have been deployed yet.

I've just noticed that the picture of FAC10 used around the site is 2.3MB compared to the FAC9 photo which is just 334kb.

The new photo looks nicer but is significantly slower to load. I suggest we reduce the file size.

Any reason why this was never deployed to Github pages? @sohilpandya @samatar26 @bo-bok ?

**Comment by rebeccaradding** [comment]
@emilyb7 the photo was not deployed due to the desire to reflect photos of both Nazareth and London.

My suggestion: put cohort photos on the individual location pages, and put something else more neutral in that landing page spot.

@jsms90 @esraajb thoughts?

**Comment by bo-bok** [comment]
@emilyb7 @rebeccaradding I suspect the image wasn't deployed due to oversight, not due to a conscious decision (#413 was approved). FACN1/FAC10 has finished, so deploying the image has little value now. 

What would be useful IMO is to have a conversation about how we want to represent the different campuses (in a sensible and fair to all way) ahead of FAC11 starting next week? A slideshow has previously been suggested, which seems better than removing any images of cohorts from the homepage when that's the heart of what we do.

**Comment by emilyb7** [comment]
@bo-bok 👍🏻 

Given that #413 has been merged into master though, the new image will go live as soon as we deploy any other changes to the site (we're currently working on the apply page).

**Comment by jsms90** [comment]
@bo-bok Couldn't agree more. You can find my suggestion about how to go about representing our community #425  (originally posted as part of a larger point in `master-reference` https://github.com/foundersandcoders/master-reference/issues/236 because I assumed more people would see it there :wink:)

@emilyb7 Would you like to sort out the problem of file size, before we deploy my changes to the application pages?

**Comment by emilyb7** [comment]
@jsms90 done and I've assigned the PR to you. The photo is still seems quite slow to load compared to the old one...

**Comment by jsms90** [comment]
@emilyb7 happy to close the issue?
