### ISSUE TITLE
Fix Dan's copy

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site#474]
Currently it says: 

**Dan Sofer** Dan is the founding director of Founders & Coders C.I.C.. He has been building websites since 1995 for clients that include The Guardian and the BBC. He project managed the build of the official website of the London 2012 Olympic Games.

Should be: 

**Dan Sofer** ~Dan~ is the founding director of Founders & Coders C.I.C.. He has been building websites since 1995 for clients that include The Guardian and the BBC. He project managed the build of the official website of the London 2012 Olympic Games.

Please make suggestions to copy if it needs an update @iteles @sofer @rebeccaradding

**Comment by rebeccaradding** [comment]
Dan is the founding director of Founders & Coders C.I.C. (our London programme) and is the co-director of Founders & Coders International. He has been building websites since 1995 for clients that include The Guardian and the BBC. He project managed the build of the official website of the London 2012 Olympic Games.
